-- =====================================================================
-- NIVAAS DATABASE — Supabase (PostgreSQL) migration
-- Converted from MySQL/MariaDB (phpMyAdmin dump)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. EXTENSIONS
-- ---------------------------------------------------------------------
create extension if not exists pgcrypto;   -- gives us gen_random_uuid()

-- ---------------------------------------------------------------------
-- 0.1 Helper trigger: auto-update `updated_at` (replaces MySQL's
--     "ON UPDATE current_timestamp()")
-- ---------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ---------------------------------------------------------------------
-- 1. nivaas_users
-- ---------------------------------------------------------------------
create table nivaas_users (
  id             uuid primary key default gen_random_uuid(),
  full_name      varchar(255),
  email          varchar(255) not null unique,
  phone          varchar(20),
  password_hash  varchar(255),
  avatar_url     varchar(1000),
  city           varchar(100),
  bio            text,
  role           varchar(20) not null default 'customer'
                   check (role in ('customer','owner','admin')),
  is_verified    boolean not null default false,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create trigger trg_users_updated_at
  before update on nivaas_users
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------
-- 2. nivaas_cities
-- ---------------------------------------------------------------------
create table nivaas_cities (
  id          integer generated by default as identity primary key,
  name        varchar(100) not null unique,
  state       varchar(100) not null,
  country     varchar(100) not null default 'India',
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 3. nivaas_amenities
-- ---------------------------------------------------------------------
create table nivaas_amenities (
  id          integer generated by default as identity primary key,
  name        varchar(100) not null unique,
  icon        varchar(50),
  category    varchar(50),
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 4. nivaas_properties
-- ---------------------------------------------------------------------
create table nivaas_properties (
  id                 uuid primary key default gen_random_uuid(),
  owner_id           uuid not null references nivaas_users(id) on delete cascade,
  city_id            integer references nivaas_cities(id) on delete set null,
  title              varchar(500) not null,
  description        text,
  property_type      varchar(20) not null default 'Apartment'
                        check (property_type in ('Apartment','Villa','PG','Office Space','Plot','Warehouse','Farm House')),
  listing_type       varchar(10) not null default 'rent'
                        check (listing_type in ('rent','sale','pg')),
  status             varchar(20) not null default 'draft'
                        check (status in ('draft','pending_review','active','inactive','rented')),
  address            text,
  locality           varchar(255),
  city               varchar(100) not null,
  state              varchar(100),
  pincode            varchar(10),
  latitude           double precision,
  longitude          double precision,
  map_url            varchar(1000),
  bedrooms           smallint,
  bathrooms          smallint,
  balconies          smallint default 0,
  area_sqft          numeric(10,2),
  carpet_area        numeric(10,2),
  floor_number       smallint,
  total_floors       smallint,
  age_years          varchar(20),
  furnished          varchar(20) default 'Unfurnished'
                        check (furnished in ('Unfurnished','Semi-Furnished','Fully Furnished')),
  facing             varchar(20),
  parking_slots      smallint default 0,
  price              numeric(14,2) not null,
  deposit            numeric(12,2),
  maintenance_fee    numeric(10,2) default 0.00,
  brokerage          numeric(10,2) default 0.00,
  price_negotiable   boolean not null default false,
  available_from     date,
  min_lease_months   smallint default 11,
  preferred_tenants  varchar(50),
  cover_image_url    varchar(1000),
  verified           boolean not null default false,
  rera_id            varchar(100),
  views_count        integer not null default 0,
  saves_count        integer not null default 0,
  inquiries_count    integer not null default 0,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index idx_prop_owner  on nivaas_properties (owner_id);
create index idx_prop_city   on nivaas_properties (city);
create index idx_prop_status on nivaas_properties (status);
create index idx_prop_type   on nivaas_properties (property_type);
create index fk_prop_city    on nivaas_properties (city_id);

create trigger trg_properties_updated_at
  before update on nivaas_properties
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------
-- 5. nivaas_property_amenities (junction table)
-- ---------------------------------------------------------------------
create table nivaas_property_amenities (
  property_id  uuid not null references nivaas_properties(id) on delete cascade,
  amenity_id   integer not null references nivaas_amenities(id) on delete cascade,
  primary key (property_id, amenity_id)
);

-- ---------------------------------------------------------------------
-- 6. nivaas_property_images
-- ---------------------------------------------------------------------
create table nivaas_property_images (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references nivaas_properties(id) on delete cascade,
  url           varchar(1000) not null,
  storage_path  varchar(1000),
  caption       varchar(255),
  is_cover      boolean not null default false,
  sort_order    smallint not null default 0,
  created_at    timestamptz not null default now()
);

create index idx_propimg_prop on nivaas_property_images (property_id);

-- ---------------------------------------------------------------------
-- 7. nivaas_property_locations
-- ---------------------------------------------------------------------
create table nivaas_property_locations (
  id                uuid primary key default gen_random_uuid(),
  property_id       uuid not null unique references nivaas_properties(id) on delete cascade,
  google_maps_url   varchar(1000) not null,
  latitude          double precision not null,
  longitude         double precision not null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index idx_loc_lat on nivaas_property_locations (latitude);
create index idx_loc_lng on nivaas_property_locations (longitude);

create trigger trg_locations_updated_at
  before update on nivaas_property_locations
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------
-- 8. nivaas_property_visits
-- ---------------------------------------------------------------------
create table nivaas_property_visits (
  id             uuid primary key default gen_random_uuid(),
  property_id    uuid not null references nivaas_properties(id) on delete cascade,
  customer_id    uuid not null references nivaas_users(id) on delete cascade,
  owner_id       uuid not null references nivaas_users(id) on delete cascade,
  visit_date     date not null,
  visit_time     time not null,
  visit_type     varchar(20) not null default 'in_person'
                    check (visit_type in ('in_person','video_call')),
  status         varchar(20) not null default 'pending'
                    check (status in ('pending','confirmed','completed','cancelled','rescheduled')),
  notes          text,
  cancel_reason  text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index idx_visit_property on nivaas_property_visits (property_id);
create index idx_visit_customer on nivaas_property_visits (customer_id);
create index idx_visit_owner    on nivaas_property_visits (owner_id);

create trigger trg_visits_updated_at
  before update on nivaas_property_visits
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------
-- 9. nivaas_agreements
-- ---------------------------------------------------------------------
create table nivaas_agreements (
  id                uuid primary key default gen_random_uuid(),
  property_id       uuid not null references nivaas_properties(id),
  owner_id          uuid not null references nivaas_users(id),
  tenant_id         uuid not null references nivaas_users(id),
  start_date        date not null,
  end_date          date not null,
  monthly_rent      numeric(12,2) not null,
  security_deposit  numeric(12,2),
  status            varchar(20) not null default 'draft'
                       check (status in ('draft','sent','signed','expired','terminated')),
  document_url      varchar(1000),
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index idx_agr_owner  on nivaas_agreements (owner_id);
create index idx_agr_tenant on nivaas_agreements (tenant_id);
create index fk_agr_prop    on nivaas_agreements (property_id);

create trigger trg_agreements_updated_at
  before update on nivaas_agreements
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------
-- 10. nivaas_rent_payments
-- ---------------------------------------------------------------------
create table nivaas_rent_payments (
  id              uuid primary key default gen_random_uuid(),
  agreement_id    uuid not null references nivaas_agreements(id) on delete cascade,
  amount          numeric(12,2) not null,
  due_date        date not null,
  paid_date       date,
  status          varchar(20) not null default 'pending'
                     check (status in ('pending','paid','overdue','waived')),
  payment_method  varchar(50),
  transaction_id  varchar(100),
  notes           text,
  created_at      timestamptz not null default now()
);

create index idx_pay_agreement on nivaas_rent_payments (agreement_id);

-- ---------------------------------------------------------------------
-- 11. nivaas_reviews
-- ---------------------------------------------------------------------
create table nivaas_reviews (
  id            uuid primary key default gen_random_uuid(),
  property_id   uuid not null references nivaas_properties(id) on delete cascade,
  reviewer_id   uuid not null references nivaas_users(id) on delete cascade,
  rating        smallint not null check (rating between 1 and 5),
  comment       text,
  created_at    timestamptz not null default now(),
  unique (property_id, reviewer_id)
);

-- ---------------------------------------------------------------------
-- 12. nivaas_saved_properties
-- ---------------------------------------------------------------------
create table nivaas_saved_properties (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references nivaas_users(id) on delete cascade,
  property_id  uuid not null references nivaas_properties(id) on delete cascade,
  saved_at     timestamptz not null default now(),
  unique (user_id, property_id)
);

create index idx_saved_user on nivaas_saved_properties (user_id);
create index fk_saved_prop  on nivaas_saved_properties (property_id);

-- ---------------------------------------------------------------------
-- 13. nivaas_inquiries
-- ---------------------------------------------------------------------
create table nivaas_inquiries (
  id           uuid primary key default gen_random_uuid(),
  property_id  uuid not null references nivaas_properties(id) on delete cascade,
  customer_id  uuid not null references nivaas_users(id),
  owner_id     uuid not null references nivaas_users(id),
  message      text,
  status       varchar(20) not null default 'pending'
                  check (status in ('pending','responded','scheduled','closed')),
  visit_date   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index idx_inq_customer on nivaas_inquiries (customer_id);
create index idx_inq_owner    on nivaas_inquiries (owner_id);
create index idx_inq_prop     on nivaas_inquiries (property_id);

create trigger trg_inquiries_updated_at
  before update on nivaas_inquiries
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------
-- 14. nivaas_messages
-- ---------------------------------------------------------------------
create table nivaas_messages (
  id           uuid primary key default gen_random_uuid(),
  sender_id    uuid not null references nivaas_users(id) on delete cascade,
  receiver_id  uuid not null references nivaas_users(id) on delete cascade,
  property_id  uuid references nivaas_properties(id) on delete set null,
  content      text not null,
  is_read      boolean not null default false,
  created_at   timestamptz not null default now()
);

create index idx_msg_sender   on nivaas_messages (sender_id);
create index idx_msg_receiver on nivaas_messages (receiver_id);
create index fk_msg_prop      on nivaas_messages (property_id);

-- =====================================================================
-- DATA
-- =====================================================================

-- Data for nivaas_users
INSERT INTO nivaas_users (id, full_name, email, phone, password_hash, avatar_url, city, bio, role, is_verified, created_at, updated_at) VALUES
  ('00000000-0000-0000-0000-000000000001', 'Rahul Mehta', 'rahul@nivaas.in', '9876543210', NULL, NULL, NULL, NULL, 'owner', true, '2026-08-11 06:37:14', '2026-08-11 06:37:14'),
  ('00000000-0000-0000-0000-000000000002', 'Priya Sharma', 'priya@nivaas.in', '9876543211', NULL, NULL, NULL, NULL, 'customer', true, '2026-08-11 06:37:14', '2026-08-11 06:37:14'),
  ('00000000-0000-0000-0000-000000000003', 'Admin User', 'admin@nivaas.in', '9876543212', NULL, NULL, NULL, NULL, 'admin', true, '2026-08-11 06:37:14', '2026-08-11 06:37:14'),
  ('43233b81-1f4d-4552-b720-c9d76ee6c576', 'jay sompura ', 'jaysompura@gmail.com', '8306929541', '$2a$10$xoNGgomLjWl6.Uhw5U0GU.QSxbA31RxnwuUH8STMpW7mp3E0/1V8G', NULL, NULL, NULL, 'owner', true, '2026-08-11 06:43:01', '2026-08-11 06:45:08'),
  ('9ec518fe-7afa-469e-a48b-cd5af968c7e2', 'harsh ', 'harshsompura@gmail.com', '8890966741', '$2a$10$Qy2pJI8YdJG8v8.SrsPw0OCuE05GOJ9o2to2UZ7oxoBH144YMCIIC', NULL, NULL, NULL, 'customer', true, '2026-08-11 06:44:31', '2026-08-11 06:47:57');

-- Data for nivaas_cities
INSERT INTO nivaas_cities (id, name, state, country, is_active, created_at) VALUES
  (1, 'Ahmedabad', 'Gujarat', 'India', true, '2026-08-11 06:37:14'),
  (2, 'Surat', 'Gujarat', 'India', true, '2026-08-11 06:37:14'),
  (3, 'Vadodara', 'Gujarat', 'India', true, '2026-08-11 06:37:14'),
  (4, 'Rajkot', 'Gujarat', 'India', true, '2026-08-11 06:37:14'),
  (5, 'Gandhinagar', 'Gujarat', 'India', true, '2026-08-11 06:37:14'),
  (6, 'Bhavnagar', 'Gujarat', 'India', true, '2026-08-11 06:37:14'),
  (7, 'Mumbai', 'Maharashtra', 'India', true, '2026-08-11 06:37:14'),
  (8, 'Bangalore', 'Karnataka', 'India', true, '2026-08-11 06:37:14'),
  (9, 'Pune', 'Maharashtra', 'India', true, '2026-08-11 06:37:14'),
  (10, 'Delhi', 'Delhi', 'India', true, '2026-08-11 06:37:14');

-- Data for nivaas_amenities
INSERT INTO nivaas_amenities (id, name, icon, category, created_at) VALUES
  (1, 'WiFi', '📶', 'basic', '2026-08-11 06:37:14'),
  (2, 'Air Conditioning', '❄️', 'basic', '2026-08-11 06:37:14'),
  (3, 'Parking', '🚗', 'basic', '2026-08-11 06:37:14'),
  (4, 'Power Backup', '🔋', 'basic', '2026-08-11 06:37:14'),
  (5, 'Water Supply 24/7', '💧', 'basic', '2026-08-11 06:37:14'),
  (6, 'Gas Pipeline', '🔥', 'basic', '2026-08-11 06:37:14'),
  (7, 'Lift/Elevator', '🛗', 'basic', '2026-08-11 06:37:14'),
  (8, 'CCTV Security', '📷', 'security', '2026-08-11 06:37:14'),
  (9, 'Security Guard', '💂', 'security', '2026-08-11 06:37:14'),
  (10, 'Intercom', '📞', 'security', '2026-08-11 06:37:14'),
  (11, 'Gym', '🏋️', 'recreation', '2026-08-11 06:37:14'),
  (12, 'Swimming Pool', '🏊', 'recreation', '2026-08-11 06:37:14'),
  (13, 'Clubhouse', '🏛️', 'recreation', '2026-08-11 06:37:14'),
  (14, 'Children Play Area', '🛝', 'recreation', '2026-08-11 06:37:14'),
  (15, 'Jogging Track', '🏃', 'recreation', '2026-08-11 06:37:14'),
  (16, 'Housekeeping', '🧹', 'service', '2026-08-11 06:37:14'),
  (17, 'Laundry', '👕', 'service', '2026-08-11 06:37:14'),
  (18, 'Meals Included', '🍽️', 'service', '2026-08-11 06:37:14'),
  (19, 'Pet Friendly', '🐾', 'lifestyle', '2026-08-11 06:37:14'),
  (20, 'Balcony', '🌅', 'lifestyle', '2026-08-11 06:37:14');

-- Data for nivaas_properties
INSERT INTO nivaas_properties (id, owner_id, city_id, title, description, property_type, listing_type, status, address, locality, city, state, pincode, latitude, longitude, map_url, bedrooms, bathrooms, balconies, area_sqft, carpet_area, floor_number, total_floors, age_years, furnished, facing, parking_slots, price, deposit, maintenance_fee, brokerage, price_negotiable, available_from, min_lease_months, preferred_tenants, cover_image_url, verified, rera_id, views_count, saves_count, inquiries_count, created_at, updated_at) VALUES
  ('1f100253-6351-4709-a9b1-ad9c57b088e6', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test pg a', NULL, 'PG', 'rent', 'active', 'Vijay Cross Road, Above Ahmedabad Reading Library, Opp. Dawat E Khas Restaurant, Ahmedabad 380009', 'Navrangpura', 'Ahmedabad', NULL, NULL, 23.0227901, 72.4884302, 'https://maps.app.goo.gl/1WuHRnjotnQxLuFk6', 1, 1, 0, 750.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 22000.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/1705a97c-34e8-440c-be88-29d07260363d.jpg', false, NULL, 2, 0, 0, '2026-08-14 10:54:03', '2026-08-15 05:20:32'),
  ('2fab4e66-88ae-4737-bd60-680857cee48a', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test v5', NULL, 'Apartment', 'rent', 'active', 'Om Residency, Tarsali Road, Near Makarpura GIDC', 'Tarsali', 'Vadodara', NULL, NULL, 22.2701057, 73.187731, 'https://maps.app.goo.gl/7MCjhCgiXehob1zB6', 1, 1, 0, 750.00, NULL, NULL, NULL, NULL, 'Semi-Furnished', NULL, 0, 23000.00, 50000.00, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/b6c8f30e-845a-4839-8620-e3ce1a5eb04d.jpg', false, NULL, 8, 0, 0, '2026-08-14 10:20:39', '2026-08-14 11:18:09'),
  ('48a28bd0-29a7-433a-b064-ef7071422874', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test', NULL, 'Apartment', 'rent', 'active', 'Darshan Apartments, Telephone Exchange Rd, Shastrinagar, Naranpura, Ahmedabad, Gujarat 380063', 'Shastrinagar', 'Ahmedabad', NULL, NULL, 23.0620896, 72.5478755, 'https://maps.app.goo.gl/RMQEw8JKVYLh76PE7', 2, 1, 0, 800.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 22000.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/07bf6dba-1be3-4ae7-a13b-f4f85a29c18b.jpg', false, NULL, 12, 0, 0, '2026-08-14 08:08:00', '2026-08-14 11:41:30'),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test s 1', NULL, 'Apartment', 'rent', 'active', 'Opp. Celebrity Greens, Vesu Main Road, Vesu, Surat, Gujarat 395007', 'Vesu', 'Surat', NULL, NULL, 21.1313057, 72.7727157, 'https://maps.app.goo.gl/tU6FoZzScqQHKsdB7', 2, 2, 0, 1200.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 44000.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/d60871d2-fed5-4376-8d0b-d48a20fdded2.jpg', false, NULL, 1, 0, 0, '2026-08-14 10:30:02', '2026-08-14 10:35:47'),
  ('5c066eba-72bc-449e-bc8e-3a3654995142', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test v3', NULL, 'Apartment', 'rent', 'active', 'Tulsi Residency, Lalbaug Road, Near Eva Mall', 'Manjalpur', 'Vadodara', NULL, NULL, 22.2721308, 73.1941157, 'https://maps.app.goo.gl/HigyBPcbChVq9AeY7', 3, 2, 0, 1280.00, NULL, NULL, NULL, NULL, 'Semi-Furnished', NULL, 0, 56300.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/2d2ce5fd-c4c0-4ea5-8241-8c13efaba848.jpg', false, NULL, 1, 0, 0, '2026-08-14 10:15:27', '2026-08-14 10:36:19'),
  ('5c170c4a-c9ca-41b2-9567-906dd808f3d5', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test v4', NULL, 'Apartment', 'rent', 'active', 'Sky View Residency, Sama-Savli Road, Near Navrachana School', 'Sama', 'Vadodara', NULL, NULL, 22.6623525, 72.9406453, 'https://maps.app.goo.gl/vuMSHDLsbAagKvor6', 3, 2, 0, 1030.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 41500.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/93ad3278-e6d4-47f1-a381-4a4f607af999.png', false, NULL, 3, 0, 0, '2026-08-14 10:18:24', '2026-08-14 10:44:09'),
  ('6f5fec3a-b895-49ae-a672-ebbe2d63a78b', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test v', NULL, 'Apartment', 'rent', 'active', 'Shree Krishna Apartment, RC Dutt Road, Near Centre Square Mall', 'Alkapuri', 'Vadodara', NULL, NULL, 22.6649547, 72.8667705, 'https://maps.app.goo.gl/LVVgRhdHG5H1EJ7L9', 3, 2, 0, 1099.00, NULL, NULL, NULL, NULL, 'Unfurnished', NULL, 0, 44000.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/012aae3c-cc89-4033-b75a-6df026a0b2fa.png', false, NULL, 1, 0, 0, '2026-08-14 10:10:49', '2026-08-14 10:10:59'),
  ('9dfba842-2455-4626-84ff-bb98c6002831', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test v2', NULL, 'Apartment', 'rent', 'active', 'Shivalik Heights, Gotri Main Road, Near Yash Complex', 'Gotri', 'Vadodara', NULL, NULL, 22.3116287, 73.0946421, 'https://maps.app.goo.gl/FcRhtE6NnKbha3zH7', 2, 1, 0, 900.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 28000.00, 50000.00, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/0bc85220-87d2-40d3-8445-8ef24755e0dd.jpg', false, NULL, 2, 0, 0, '2026-08-14 10:13:33', '2026-08-14 11:18:04'),
  ('b6f3e365-aa8a-4414-86a0-e8823fddadec', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test s 33', NULL, 'Apartment', 'sale', 'active', 'Anand Mahal Lane, Adajan Gam, Adajan, Surat, Gujarat 395009', 'Adajan', 'Surat', NULL, NULL, 21.1951158, 72.7936349, 'https://maps.app.goo.gl/eWx5QmYKo6eccNna9', 3, 2, 0, 1200.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 8500000.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/6b22fa20-3bf9-44c9-9af6-90f00d2a3585.jpg', false, NULL, 0, 0, 0, '2026-08-14 10:34:24', '2026-08-14 10:34:24'),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test 2', NULL, 'Villa', 'rent', 'active', 'Krushnam Villa, Off, Sindhu Bhavan Marg, PRL Colony, Bodakdev, Ahmedabad, Gujarat 380058', 'Sindhu Bhavan', 'Ahmedabad', NULL, NULL, 23.0406701, 72.4668932, 'https://maps.app.goo.gl/UzVjpBrqaA8DeMeH6', 5, 6, 0, 1800.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 24974.00, 50000.00, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/5e0cba1a-c839-405b-9655-2dd02c0b0c83.jpg', false, NULL, 8, 0, 0, '2026-08-14 09:57:53', '2026-08-14 13:41:11'),
  ('cf09b4a2-5ecd-4212-966b-9234eaf820b9', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test a1', NULL, 'Apartment', 'rent', 'active', 'Plot No. 21, Shanti Sadan Society, Near Parimal Garden, Ellisbridge, Ahmedabad 380006', 'Ambawadi', 'Ahmedabad', NULL, NULL, 23.0179628, 72.557104, 'https://maps.app.goo.gl/BycWfVNdB1nDXpby5', 3, 2, 0, 1023.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 20200.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/22f1f6eb-4994-49b1-a01e-234da5d3d5a6.png', false, NULL, 3, 0, 0, '2026-08-14 10:48:17', '2026-08-14 11:17:48'),
  ('d2021cb2-35ee-4011-913e-e3981b576470', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test v5', NULL, 'PG', 'rent', 'active', 'Sai Residency, Nizampura Main Road, Near Swaminarayan Temple', 'Nizampura', 'Vadodara', NULL, NULL, 22.3151214, 73.2108421, 'https://maps.app.goo.gl/WZQHwYMX9R9AV4ps5', 1, 1, 0, 600.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 41500.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/e7963d68-efc7-4eb7-92c3-7a2ad185e1d9.png', false, NULL, 2, 0, 0, '2026-08-14 10:23:54', '2026-08-14 10:44:28'),
  ('d41b3427-8fe5-4fd0-b809-8580314db8cf', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test a 4', NULL, 'Apartment', 'rent', 'active', 'Opp. Shakti School, Near Shyamal Cross Road, Satellite, Ahmedabad 380015', 'Satellite', 'Ahmedabad', NULL, NULL, 23.0113135, 72.5308838, 'https://maps.app.goo.gl/w9Zz3SLjaTryfugZ6', 2, 1, 0, 1200.00, NULL, NULL, NULL, NULL, 'Semi-Furnished', NULL, 0, 25500.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/a66ed305-223b-4f31-8e9e-86d1ead40941.png', false, NULL, 6, 0, 0, '2026-08-14 10:51:43', '2026-08-14 14:03:11'),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test a 2', NULL, 'Apartment', 'rent', 'active', 'Gulbai Tekra', 'Gulbai Tekra', 'Ahmedabad', NULL, NULL, 23.0601085, 72.4341376, 'https://maps.app.goo.gl/F8s4mhtnJh3KAULU9', 2, 2, 0, 800.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 16100.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/e85ceff3-6682-4b30-b925-c7021723cec1.jpg', false, NULL, 4, 0, 0, '2026-08-14 10:49:59', '2026-08-14 11:17:45'),
  ('ef0347b7-d071-4172-90ce-d17db80543c1', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'test s2', NULL, 'Apartment', 'rent', 'active', 'Bhesan Road, Opp. Madhav Baug, Ugat, Surat, Gujarat 395005', 'Ugat', 'Surat', NULL, NULL, 21.2212858, 72.7723594, 'https://maps.app.goo.gl/SEUdvDa91NJntgDq5', 2, 1, 0, 800.00, NULL, NULL, NULL, NULL, 'Semi-Furnished', NULL, 0, 29300.00, NULL, 0.00, 0.00, false, NULL, 11, NULL, 'http://localhost:4000/uploads/8e9bbfc4-b9fa-45e6-9967-c61a4c6906ab.jpg', false, NULL, 1, 0, 0, '2026-08-14 10:31:35', '2026-08-14 10:35:42'),
  ('00000000-0000-0000-0001-000000000001', '00000000-0000-0000-0000-000000000001', 1, '3 BHK Luxury Apartment in Prahlad Nagar', NULL, 'Apartment', 'rent', 'active', 'B-402, Sky Vista, Prahlad Nagar', 'Prahlad Nagar', 'Ahmedabad', 'Gujarat', '380015', 23.0225, 72.5714, NULL, 3, 2, 0, 1450.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 35000.00, 100000.00, 0.00, 0.00, false, '2025-02-01', 11, NULL, 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', true, NULL, 6, 0, 0, '2026-08-11 06:37:15', '2026-08-14 10:39:02'),
  ('00000000-0000-0000-0001-000000000002', '00000000-0000-0000-0000-000000000001', 1, '2 BHK Modern Flat in Satellite', NULL, 'Apartment', 'rent', 'active', 'C-201, Green Meadows, Satellite', 'Satellite', 'Ahmedabad', 'Gujarat', '380015', 23.03, 72.52, NULL, 2, 2, 0, 1100.00, NULL, NULL, NULL, NULL, 'Semi-Furnished', NULL, 0, 22000.00, 66000.00, 0.00, 0.00, false, '2025-01-15', 11, NULL, 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', true, NULL, 4, 0, 0, '2026-08-11 06:37:15', '2026-08-14 10:34:56'),
  ('00000000-0000-0000-0001-000000000003', '00000000-0000-0000-0000-000000000001', 2, 'Spacious 4 BHK Villa in Vesu', NULL, 'Villa', 'sale', 'active', '12, Palm Avenue, Vesu', 'Vesu', 'Surat', 'Gujarat', '395007', 21.1702, 72.7856, NULL, 4, 4, 0, 2800.00, NULL, NULL, NULL, NULL, 'Fully Furnished', NULL, 0, 8500000.00, 0.00, 0.00, 0.00, false, '2025-03-01', 11, NULL, 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', true, NULL, 5, 0, 0, '2026-08-11 06:37:15', '2026-08-14 12:42:59');

-- Data for nivaas_property_amenities
INSERT INTO nivaas_property_amenities (property_id, amenity_id) VALUES
  ('1f100253-6351-4709-a9b1-ad9c57b088e6', 1),
  ('1f100253-6351-4709-a9b1-ad9c57b088e6', 2),
  ('1f100253-6351-4709-a9b1-ad9c57b088e6', 5),
  ('1f100253-6351-4709-a9b1-ad9c57b088e6', 6),
  ('1f100253-6351-4709-a9b1-ad9c57b088e6', 9),
  ('1f100253-6351-4709-a9b1-ad9c57b088e6', 20),
  ('2fab4e66-88ae-4737-bd60-680857cee48a', 5),
  ('2fab4e66-88ae-4737-bd60-680857cee48a', 6),
  ('2fab4e66-88ae-4737-bd60-680857cee48a', 7),
  ('2fab4e66-88ae-4737-bd60-680857cee48a', 9),
  ('48a28bd0-29a7-433a-b064-ef7071422874', 2),
  ('48a28bd0-29a7-433a-b064-ef7071422874', 3),
  ('48a28bd0-29a7-433a-b064-ef7071422874', 5),
  ('48a28bd0-29a7-433a-b064-ef7071422874', 6),
  ('48a28bd0-29a7-433a-b064-ef7071422874', 7),
  ('48a28bd0-29a7-433a-b064-ef7071422874', 8),
  ('48a28bd0-29a7-433a-b064-ef7071422874', 9),
  ('48a28bd0-29a7-433a-b064-ef7071422874', 20),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 1),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 2),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 3),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 5),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 6),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 7),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 8),
  ('545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 20),
  ('5c066eba-72bc-449e-bc8e-3a3654995142', 6),
  ('5c066eba-72bc-449e-bc8e-3a3654995142', 7),
  ('5c066eba-72bc-449e-bc8e-3a3654995142', 8),
  ('5c066eba-72bc-449e-bc8e-3a3654995142', 9),
  ('5c066eba-72bc-449e-bc8e-3a3654995142', 20),
  ('5c170c4a-c9ca-41b2-9567-906dd808f3d5', 2),
  ('5c170c4a-c9ca-41b2-9567-906dd808f3d5', 3),
  ('5c170c4a-c9ca-41b2-9567-906dd808f3d5', 5),
  ('5c170c4a-c9ca-41b2-9567-906dd808f3d5', 6),
  ('6f5fec3a-b895-49ae-a672-ebbe2d63a78b', 5),
  ('6f5fec3a-b895-49ae-a672-ebbe2d63a78b', 7),
  ('6f5fec3a-b895-49ae-a672-ebbe2d63a78b', 8),
  ('6f5fec3a-b895-49ae-a672-ebbe2d63a78b', 9),
  ('6f5fec3a-b895-49ae-a672-ebbe2d63a78b', 20),
  ('9dfba842-2455-4626-84ff-bb98c6002831', 2),
  ('9dfba842-2455-4626-84ff-bb98c6002831', 3),
  ('9dfba842-2455-4626-84ff-bb98c6002831', 5),
  ('9dfba842-2455-4626-84ff-bb98c6002831', 6),
  ('9dfba842-2455-4626-84ff-bb98c6002831', 7),
  ('9dfba842-2455-4626-84ff-bb98c6002831', 8),
  ('9dfba842-2455-4626-84ff-bb98c6002831', 9),
  ('9dfba842-2455-4626-84ff-bb98c6002831', 20),
  ('b6f3e365-aa8a-4414-86a0-e8823fddadec', 5),
  ('b6f3e365-aa8a-4414-86a0-e8823fddadec', 6),
  ('b6f3e365-aa8a-4414-86a0-e8823fddadec', 7),
  ('b6f3e365-aa8a-4414-86a0-e8823fddadec', 8),
  ('b6f3e365-aa8a-4414-86a0-e8823fddadec', 9),
  ('b6f3e365-aa8a-4414-86a0-e8823fddadec', 20),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', 2),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', 3),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', 5),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', 6),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', 8),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', 9),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', 14),
  ('cefce6db-7025-45f8-abf4-952cc570b90d', 20),
  ('cf09b4a2-5ecd-4212-966b-9234eaf820b9', 1),
  ('cf09b4a2-5ecd-4212-966b-9234eaf820b9', 2),
  ('cf09b4a2-5ecd-4212-966b-9234eaf820b9', 3),
  ('cf09b4a2-5ecd-4212-966b-9234eaf820b9', 5),
  ('cf09b4a2-5ecd-4212-966b-9234eaf820b9', 6),
  ('cf09b4a2-5ecd-4212-966b-9234eaf820b9', 7),
  ('cf09b4a2-5ecd-4212-966b-9234eaf820b9', 20),
  ('d2021cb2-35ee-4011-913e-e3981b576470', 1),
  ('d2021cb2-35ee-4011-913e-e3981b576470', 5),
  ('d2021cb2-35ee-4011-913e-e3981b576470', 9),
  ('d2021cb2-35ee-4011-913e-e3981b576470', 16),
  ('d2021cb2-35ee-4011-913e-e3981b576470', 17),
  ('d2021cb2-35ee-4011-913e-e3981b576470', 20),
  ('d41b3427-8fe5-4fd0-b809-8580314db8cf', 5),
  ('d41b3427-8fe5-4fd0-b809-8580314db8cf', 6),
  ('d41b3427-8fe5-4fd0-b809-8580314db8cf', 7),
  ('d41b3427-8fe5-4fd0-b809-8580314db8cf', 8),
  ('d41b3427-8fe5-4fd0-b809-8580314db8cf', 20),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 1),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 2),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 3),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 5),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 6),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 7),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 8),
  ('ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 20),
  ('ef0347b7-d071-4172-90ce-d17db80543c1', 5),
  ('ef0347b7-d071-4172-90ce-d17db80543c1', 6),
  ('ef0347b7-d071-4172-90ce-d17db80543c1', 8),
  ('ef0347b7-d071-4172-90ce-d17db80543c1', 9),
  ('00000000-0000-0000-0001-000000000001', 1),
  ('00000000-0000-0000-0001-000000000001', 2),
  ('00000000-0000-0000-0001-000000000001', 3),
  ('00000000-0000-0000-0001-000000000001', 7),
  ('00000000-0000-0000-0001-000000000001', 8),
  ('00000000-0000-0000-0001-000000000001', 11),
  ('00000000-0000-0000-0001-000000000002', 1),
  ('00000000-0000-0000-0001-000000000002', 3);

INSERT INTO nivaas_property_amenities (property_id, amenity_id) VALUES
  ('00000000-0000-0000-0001-000000000002', 7),
  ('00000000-0000-0000-0001-000000000003', 3),
  ('00000000-0000-0000-0001-000000000003', 11),
  ('00000000-0000-0000-0001-000000000003', 12),
  ('00000000-0000-0000-0001-000000000003', 20);

-- Data for nivaas_property_images
INSERT INTO nivaas_property_images (id, property_id, url, storage_path, caption, is_cover, sort_order, created_at) VALUES
  ('0375f5b5-c4d7-4c69-b9eb-a58df89ffe0f', '5c066eba-72bc-449e-bc8e-3a3654995142', 'http://localhost:4000/uploads/10dd5ee7-a0c5-46ff-a755-40103b82e5ba.jpg', '10dd5ee7-a0c5-46ff-a755-40103b82e5ba.jpg', NULL, false, 1, '2026-08-14 10:15:27'),
  ('25ed56b8-fd9d-4d54-ac64-9db570d96b10', 'cf09b4a2-5ecd-4212-966b-9234eaf820b9', 'http://localhost:4000/uploads/428ea53b-99e1-4a17-ba95-c1a214145326.jpg', '428ea53b-99e1-4a17-ba95-c1a214145326.jpg', NULL, false, 1, '2026-08-14 10:48:18'),
  ('2c779d7a-5756-4458-8a8d-8117af8d69ed', 'd41b3427-8fe5-4fd0-b809-8580314db8cf', 'http://localhost:4000/uploads/26a99637-3465-4492-b558-c36842faac76.jpg', '26a99637-3465-4492-b558-c36842faac76.jpg', NULL, false, 1, '2026-08-14 10:51:44'),
  ('30af0d99-bdd1-4c09-b2da-6f668161bda9', 'cf09b4a2-5ecd-4212-966b-9234eaf820b9', 'http://localhost:4000/uploads/22f1f6eb-4994-49b1-a01e-234da5d3d5a6.png', '22f1f6eb-4994-49b1-a01e-234da5d3d5a6.png', NULL, true, 0, '2026-08-14 10:48:18'),
  ('34284925-b2a5-44cc-9ca0-908c41a9184f', '5c170c4a-c9ca-41b2-9567-906dd808f3d5', 'http://localhost:4000/uploads/56804008-b529-442a-b238-ad10ff836654.jpg', '56804008-b529-442a-b238-ad10ff836654.jpg', NULL, false, 1, '2026-08-14 10:18:25'),
  ('380ca67b-8bda-41e7-857c-0721a646e018', 'cefce6db-7025-45f8-abf4-952cc570b90d', 'http://localhost:4000/uploads/5e0cba1a-c839-405b-9655-2dd02c0b0c83.jpg', '5e0cba1a-c839-405b-9655-2dd02c0b0c83.jpg', NULL, true, 0, '2026-08-14 09:57:53'),
  ('39d6e546-a89e-4fe0-a26b-40c775711558', '545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 'http://localhost:4000/uploads/d60871d2-fed5-4376-8d0b-d48a20fdded2.jpg', 'd60871d2-fed5-4376-8d0b-d48a20fdded2.jpg', NULL, true, 0, '2026-08-14 10:30:02'),
  ('4351a846-abb3-4538-9a29-a435f09d59c4', 'd41b3427-8fe5-4fd0-b809-8580314db8cf', 'http://localhost:4000/uploads/a66ed305-223b-4f31-8e9e-86d1ead40941.png', 'a66ed305-223b-4f31-8e9e-86d1ead40941.png', NULL, true, 0, '2026-08-14 10:51:44'),
  ('52e8912c-336e-4f83-9856-53cb03bb604c', '1f100253-6351-4709-a9b1-ad9c57b088e6', 'http://localhost:4000/uploads/1705a97c-34e8-440c-be88-29d07260363d.jpg', '1705a97c-34e8-440c-be88-29d07260363d.jpg', NULL, true, 0, '2026-08-14 10:54:03'),
  ('55195889-b9b2-4d34-8c65-b86371e474bd', 'd2021cb2-35ee-4011-913e-e3981b576470', 'http://localhost:4000/uploads/e3323b02-f6c4-4f8f-a478-9f0c0fdc909a.jpg', 'e3323b02-f6c4-4f8f-a478-9f0c0fdc909a.jpg', NULL, false, 1, '2026-08-14 10:23:54'),
  ('6e4361f6-0dd4-4b10-8346-b1c7298c4d40', '5c170c4a-c9ca-41b2-9567-906dd808f3d5', 'http://localhost:4000/uploads/93ad3278-e6d4-47f1-a381-4a4f607af999.png', '93ad3278-e6d4-47f1-a381-4a4f607af999.png', NULL, true, 0, '2026-08-14 10:18:25'),
  ('79808289-5820-43ba-9bf3-8520d0caca64', 'ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 'http://localhost:4000/uploads/ed4e6362-2f51-40cb-b86e-d7134052733b.jpg', 'ed4e6362-2f51-40cb-b86e-d7134052733b.jpg', NULL, false, 2, '2026-08-14 10:49:59'),
  ('7d92c037-50b0-4930-a793-ee59f051343b', '6f5fec3a-b895-49ae-a672-ebbe2d63a78b', 'http://localhost:4000/uploads/012aae3c-cc89-4033-b75a-6df026a0b2fa.png', '012aae3c-cc89-4033-b75a-6df026a0b2fa.png', NULL, true, 0, '2026-08-14 10:10:50'),
  ('7ec8de36-c984-4cf6-9988-f94312c673d0', '9dfba842-2455-4626-84ff-bb98c6002831', 'http://localhost:4000/uploads/0bc85220-87d2-40d3-8445-8ef24755e0dd.jpg', '0bc85220-87d2-40d3-8445-8ef24755e0dd.jpg', NULL, true, 0, '2026-08-14 10:13:33'),
  ('83cde569-2965-424a-99a1-19a73e5f1886', 'ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 'http://localhost:4000/uploads/fd1748fb-e001-49e3-896c-287640aadca4.jpg', 'fd1748fb-e001-49e3-896c-287640aadca4.jpg', NULL, false, 1, '2026-08-14 10:49:59'),
  ('9302a180-85c3-4e6f-9e3d-20f84eec106e', 'd41b3427-8fe5-4fd0-b809-8580314db8cf', 'http://localhost:4000/uploads/0e07c54b-28e9-492f-abb8-807688a3f4eb.jpg', '0e07c54b-28e9-492f-abb8-807688a3f4eb.jpg', NULL, false, 2, '2026-08-14 10:51:44'),
  ('94176ac2-8be7-47f0-95fc-7a86b09912ce', '2fab4e66-88ae-4737-bd60-680857cee48a', 'http://localhost:4000/uploads/b6c8f30e-845a-4839-8620-e3ce1a5eb04d.jpg', 'b6c8f30e-845a-4839-8620-e3ce1a5eb04d.jpg', NULL, true, 0, '2026-08-14 10:20:39'),
  ('965c08ef-fc94-4d5e-b77b-ebd95a77cb22', 'd2021cb2-35ee-4011-913e-e3981b576470', 'http://localhost:4000/uploads/e7963d68-efc7-4eb7-92c3-7a2ad185e1d9.png', 'e7963d68-efc7-4eb7-92c3-7a2ad185e1d9.png', NULL, true, 0, '2026-08-14 10:23:54'),
  ('b246148a-8630-4021-bae1-21335f5cfa36', 'ef0347b7-d071-4172-90ce-d17db80543c1', 'http://localhost:4000/uploads/79973a59-c2bd-4525-804b-65ebe74477ff.jpg', '79973a59-c2bd-4525-804b-65ebe74477ff.jpg', NULL, false, 1, '2026-08-14 10:31:35'),
  ('b26e8fa4-9c49-475a-bba6-d3f9de217de8', '2fab4e66-88ae-4737-bd60-680857cee48a', 'http://localhost:4000/uploads/92878e18-33b2-4225-b448-0981c056e36f.jpg', '92878e18-33b2-4225-b448-0981c056e36f.jpg', NULL, false, 1, '2026-08-14 10:20:39'),
  ('b80040ee-2eb7-46aa-b63a-1d7e3fa7e83b', '48a28bd0-29a7-433a-b064-ef7071422874', 'http://localhost:4000/uploads/3cabdcad-a075-402c-9db5-be3171d1126d.jpg', '3cabdcad-a075-402c-9db5-be3171d1126d.jpg', NULL, false, 1, '2026-08-14 08:08:00'),
  ('bcee1619-3987-4f95-a66b-fde136497833', '5c066eba-72bc-449e-bc8e-3a3654995142', 'http://localhost:4000/uploads/2d2ce5fd-c4c0-4ea5-8241-8c13efaba848.jpg', '2d2ce5fd-c4c0-4ea5-8241-8c13efaba848.jpg', NULL, true, 0, '2026-08-14 10:15:27'),
  ('bffd381f-4a72-45a0-8b5c-1d4353e12cb7', '545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 'http://localhost:4000/uploads/be8126c3-8116-48f2-ac6b-be340b08eeb0.jpg', 'be8126c3-8116-48f2-ac6b-be340b08eeb0.jpg', NULL, false, 1, '2026-08-14 10:30:02'),
  ('c0adad30-2407-4641-b104-ceaff77e820b', '6f5fec3a-b895-49ae-a672-ebbe2d63a78b', 'http://localhost:4000/uploads/803ce7de-1789-4e6c-9907-6df4237be2c5.jpg', '803ce7de-1789-4e6c-9907-6df4237be2c5.jpg', NULL, false, 1, '2026-08-14 10:10:50'),
  ('c452b945-727a-4be5-b805-03bea6ab456e', '48a28bd0-29a7-433a-b064-ef7071422874', 'http://localhost:4000/uploads/07bf6dba-1be3-4ae7-a13b-f4f85a29c18b.jpg', '07bf6dba-1be3-4ae7-a13b-f4f85a29c18b.jpg', NULL, true, 0, '2026-08-14 08:08:00'),
  ('ccff4686-a807-4004-9561-efa3da02d261', 'b6f3e365-aa8a-4414-86a0-e8823fddadec', 'http://localhost:4000/uploads/6b22fa20-3bf9-44c9-9af6-90f00d2a3585.jpg', '6b22fa20-3bf9-44c9-9af6-90f00d2a3585.jpg', NULL, true, 0, '2026-08-14 10:34:24'),
  ('cdbacf5d-b809-49ce-9d53-3fcf7b22e3ad', 'ef0347b7-d071-4172-90ce-d17db80543c1', 'http://localhost:4000/uploads/8e9bbfc4-b9fa-45e6-9967-c61a4c6906ab.jpg', '8e9bbfc4-b9fa-45e6-9967-c61a4c6906ab.jpg', NULL, true, 0, '2026-08-14 10:31:35'),
  ('dd7e6945-6356-4364-acfe-e912c323e1fe', '1f100253-6351-4709-a9b1-ad9c57b088e6', 'http://localhost:4000/uploads/f7e4c797-f6eb-4cdc-87ab-7706912501f0.jpg', 'f7e4c797-f6eb-4cdc-87ab-7706912501f0.jpg', NULL, false, 1, '2026-08-14 10:54:03'),
  ('f076958d-bdbb-4a6f-b4be-d4b426e34974', 'ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 'http://localhost:4000/uploads/e85ceff3-6682-4b30-b925-c7021723cec1.jpg', 'e85ceff3-6682-4b30-b925-c7021723cec1.jpg', NULL, true, 0, '2026-08-14 10:49:59'),
  ('f6df8e5b-3513-4732-942f-c5feae1eb130', 'cefce6db-7025-45f8-abf4-952cc570b90d', 'http://localhost:4000/uploads/e8171ac8-ac8c-4777-9c3f-f3ac4ffce115.jpg', 'e8171ac8-ac8c-4777-9c3f-f3ac4ffce115.jpg', NULL, false, 1, '2026-08-14 09:57:53'),
  ('fa77a8d9-71b9-4046-933b-c6ca2227a31e', 'b6f3e365-aa8a-4414-86a0-e8823fddadec', 'http://localhost:4000/uploads/f7c69c9b-f9c9-4f0a-bbe4-827acd952582.jpg', 'f7c69c9b-f9c9-4f0a-bbe4-827acd952582.jpg', NULL, false, 1, '2026-08-14 10:34:24'),
  ('fe1aa195-9439-46d4-ad9e-64e0d3e9b22e', '9dfba842-2455-4626-84ff-bb98c6002831', 'http://localhost:4000/uploads/be361c60-dab6-4b20-959f-9ebcf3e5aceb.jpg', 'be361c60-dab6-4b20-959f-9ebcf3e5aceb.jpg', NULL, false, 1, '2026-08-14 10:13:33');

-- Data for nivaas_property_locations
INSERT INTO nivaas_property_locations (id, property_id, google_maps_url, latitude, longitude, created_at, updated_at) VALUES
  ('12455fbe-97c9-11f1-8481-04d4c4dfb00e', '5c066eba-72bc-449e-bc8e-3a3654995142', 'https://maps.app.goo.gl/HigyBPcbChVq9AeY7', 22.2721308, 73.1941157, '2026-08-14 10:15:27', '2026-08-14 10:15:27'),
  ('1bc23582-97cb-11f1-8481-04d4c4dfb00e', '545e34a0-e2ba-4a03-a0c0-cb097a7fffe1', 'https://maps.app.goo.gl/tU6FoZzScqQHKsdB7', 21.1313057, 72.7727157, '2026-08-14 10:30:02', '2026-08-14 10:30:02'),
  ('23851cb6-97ce-11f1-8481-04d4c4dfb00e', 'd41b3427-8fe5-4fd0-b809-8580314db8cf', 'https://maps.app.goo.gl/w9Zz3SLjaTryfugZ6', 23.0113135, 72.5308838, '2026-08-14 10:51:44', '2026-08-14 10:51:44'),
  ('405d9f5d-97ca-11f1-8481-04d4c4dfb00e', 'd2021cb2-35ee-4011-913e-e3981b576470', 'https://maps.app.goo.gl/WZQHwYMX9R9AV4ps5', 22.3151214, 73.2108421, '2026-08-14 10:23:54', '2026-08-14 10:23:54'),
  ('442ff5b3-97b7-11f1-bea2-04d4c4dfb00e', '48a28bd0-29a7-433a-b064-ef7071422874', 'https://maps.app.goo.gl/RMQEw8JKVYLh76PE7', 23.0620896, 72.5478755, '2026-08-14 08:08:00', '2026-08-14 08:08:00'),
  ('535f9d7d-97cb-11f1-8481-04d4c4dfb00e', 'ef0347b7-d071-4172-90ce-d17db80543c1', 'https://maps.app.goo.gl/SEUdvDa91NJntgDq5', 21.2212858, 72.7723594, '2026-08-14 10:31:35', '2026-08-14 10:31:35'),
  ('6cbe7f42-97c8-11f1-8481-04d4c4dfb00e', '6f5fec3a-b895-49ae-a672-ebbe2d63a78b', 'https://maps.app.goo.gl/LVVgRhdHG5H1EJ7L9', 22.6649547, 72.8667705, '2026-08-14 10:10:49', '2026-08-14 10:10:49'),
  ('7686085d-97ce-11f1-8481-04d4c4dfb00e', '1f100253-6351-4709-a9b1-ad9c57b088e6', 'https://maps.app.goo.gl/1WuHRnjotnQxLuFk6', 23.0227901, 72.4884302, '2026-08-14 10:54:03', '2026-08-14 10:54:03'),
  ('7be2b21e-97c9-11f1-8481-04d4c4dfb00e', '5c170c4a-c9ca-41b2-9567-906dd808f3d5', 'https://maps.app.goo.gl/vuMSHDLsbAagKvor6', 22.6623525, 72.9406453, '2026-08-14 10:18:24', '2026-08-14 10:18:24'),
  ('9e1df591-97c6-11f1-8481-04d4c4dfb00e', 'cefce6db-7025-45f8-abf4-952cc570b90d', 'https://maps.app.goo.gl/UzVjpBrqaA8DeMeH6', 23.0406701, 72.4668932, '2026-08-14 09:57:53', '2026-08-14 09:57:53'),
  ('a83ef262-97cd-11f1-8481-04d4c4dfb00e', 'cf09b4a2-5ecd-4212-966b-9234eaf820b9', 'https://maps.app.goo.gl/BycWfVNdB1nDXpby5', 23.0179628, 72.557104, '2026-08-14 10:48:17', '2026-08-14 10:48:17'),
  ('b7b4e3ae-97cb-11f1-8481-04d4c4dfb00e', 'b6f3e365-aa8a-4414-86a0-e8823fddadec', 'https://maps.app.goo.gl/eWx5QmYKo6eccNna9', 21.1951158, 72.7936349, '2026-08-14 10:34:24', '2026-08-14 10:34:24'),
  ('cc07810a-97c9-11f1-8481-04d4c4dfb00e', '2fab4e66-88ae-4737-bd60-680857cee48a', 'https://maps.app.goo.gl/7MCjhCgiXehob1zB6', 22.2701057, 73.187731, '2026-08-14 10:20:39', '2026-08-14 10:20:39'),
  ('ce72b1a5-97c8-11f1-8481-04d4c4dfb00e', '9dfba842-2455-4626-84ff-bb98c6002831', 'https://maps.app.goo.gl/FcRhtE6NnKbha3zH7', 22.3116287, 73.0946421, '2026-08-14 10:13:33', '2026-08-14 10:13:33'),
  ('e510de24-97cd-11f1-8481-04d4c4dfb00e', 'ee4aaf10-54f0-4cd5-a765-f2d44ed657c1', 'https://maps.app.goo.gl/F8s4mhtnJh3KAULU9', 23.0601085, 72.4341376, '2026-08-14 10:49:59', '2026-08-14 10:49:59');

-- Data for nivaas_messages
INSERT INTO nivaas_messages (id, sender_id, receiver_id, property_id, content, is_read, created_at) VALUES
  ('4eab7fdd-bcb0-49af-9899-92688d86f188', '9ec518fe-7afa-469e-a48b-cd5af968c7e2', '43233b81-1f4d-4552-b720-c9d76ee6c576', NULL, 'Hello, sir. I like this property. I want this property on rent, so can we meet?', true, '2026-08-11 06:50:00');


-- =====================================================================
-- ROW LEVEL SECURITY
-- Supabase requires RLS to be ON for tables exposed via the API
-- (PostgREST / supabase-js). Since Nivaas uses ITS OWN auth system
-- (bcrypt password_hash + custom Node backend, NOT Supabase Auth),
-- these policies are set to "allow everything" for now so your
-- existing app keeps working exactly like it does with plain MySQL.
--
-- IMPORTANT: tighten these later once you decide how the DB will be
-- accessed (service_role key from your backend = bypasses RLS anyway
-- and is the safest option; anon key from a browser = you MUST write
-- real policies before going to production).
-- =====================================================================

alter table nivaas_users               enable row level security;
alter table nivaas_cities              enable row level security;
alter table nivaas_amenities           enable row level security;
alter table nivaas_properties          enable row level security;
alter table nivaas_property_amenities  enable row level security;
alter table nivaas_property_images     enable row level security;
alter table nivaas_property_locations  enable row level security;
alter table nivaas_property_visits     enable row level security;
alter table nivaas_agreements          enable row level security;
alter table nivaas_rent_payments       enable row level security;
alter table nivaas_reviews             enable row level security;
alter table nivaas_saved_properties    enable row level security;
alter table nivaas_inquiries           enable row level security;
alter table nivaas_messages            enable row level security;

create policy "allow all - nivaas_users" on nivaas_users for all using (true) with check (true);
create policy "allow all - nivaas_cities" on nivaas_cities for all using (true) with check (true);
create policy "allow all - nivaas_amenities" on nivaas_amenities for all using (true) with check (true);
create policy "allow all - nivaas_properties" on nivaas_properties for all using (true) with check (true);
create policy "allow all - nivaas_property_amenities" on nivaas_property_amenities for all using (true) with check (true);
create policy "allow all - nivaas_property_images" on nivaas_property_images for all using (true) with check (true);
create policy "allow all - nivaas_property_locations" on nivaas_property_locations for all using (true) with check (true);
create policy "allow all - nivaas_property_visits" on nivaas_property_visits for all using (true) with check (true);
create policy "allow all - nivaas_agreements" on nivaas_agreements for all using (true) with check (true);
create policy "allow all - nivaas_rent_payments" on nivaas_rent_payments for all using (true) with check (true);
create policy "allow all - nivaas_reviews" on nivaas_reviews for all using (true) with check (true);
create policy "allow all - nivaas_saved_properties" on nivaas_saved_properties for all using (true) with check (true);
create policy "allow all - nivaas_inquiries" on nivaas_inquiries for all using (true) with check (true);
create policy "allow all - nivaas_messages" on nivaas_messages for all using (true) with check (true);

-- =====================================================================
-- Fix identity sequences after manual-id inserts (cities, amenities)
-- =====================================================================
select setval(pg_get_serial_sequence('nivaas_cities', 'id'), (select coalesce(max(id), 1) from nivaas_cities));
select setval(pg_get_serial_sequence('nivaas_amenities', 'id'), (select coalesce(max(id), 1) from nivaas_amenities));


-- =====================================================================
-- NIVAAS — ADDENDUM: Missing tables & production fixes
-- Run this section if you already applied the base migration above.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 15. nivaas_notifications
-- ---------------------------------------------------------------------
create table if not exists nivaas_notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references nivaas_users(id) on delete cascade,
  type        varchar(60) not null,
  title       varchar(255) not null,
  body        text,
  link        varchar(500),
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);

create index if not exists idx_notif_user   on nivaas_notifications (user_id);
create index if not exists idx_notif_unread on nivaas_notifications (user_id, is_read);

alter table nivaas_notifications enable row level security;
create policy "allow all - nivaas_notifications" on nivaas_notifications for all using (true) with check (true);

-- Rename display_order column alias: property_images already has sort_order.
-- Ensure sort_order exists (idempotent) and add display_order as alias column comment.
comment on column nivaas_property_images.sort_order is 'display_order: 0 = first/cover image';

-- Ensure cover_image_url is kept in sync when images change (helper trigger).
create or replace function sync_property_cover()
returns trigger as $$
begin
  -- After insert/update/delete on property_images, update cover_image_url
  -- on the parent property to always point to the image with is_cover = true
  -- or the lowest sort_order image if no cover is flagged.
  update nivaas_properties
  set cover_image_url = (
    select url
    from nivaas_property_images
    where property_id = coalesce(new.property_id, old.property_id)
    order by (is_cover::int) desc, sort_order asc
    limit 1
  )
  where id = coalesce(new.property_id, old.property_id);
  return coalesce(new, old);
end;
$$ language plpgsql;

drop trigger if exists trg_sync_cover_insert on nivaas_property_images;
drop trigger if exists trg_sync_cover_update on nivaas_property_images;
drop trigger if exists trg_sync_cover_delete on nivaas_property_images;

create trigger trg_sync_cover_insert
  after insert on nivaas_property_images
  for each row execute function sync_property_cover();

create trigger trg_sync_cover_update
  after update on nivaas_property_images
  for each row execute function sync_property_cover();

create trigger trg_sync_cover_delete
  after delete on nivaas_property_images
  for each row execute function sync_property_cover();

-- Cascade delete notifications and images when properties are deleted
-- (foreign key with ON DELETE CASCADE already set in base schema).

-- Fix identity sequences
select setval(pg_get_serial_sequence('nivaas_cities',    'id'), (select coalesce(max(id), 1) from nivaas_cities));
select setval(pg_get_serial_sequence('nivaas_amenities', 'id'), (select coalesce(max(id), 1) from nivaas_amenities));
