/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesMapRouteImport } from './routes/properties.map'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardVisitsRouteImport } from './routes/_authenticated/dashboard.visits'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardSavedRouteImport } from './routes/_authenticated/dashboard.saved'
import { Route as AuthenticatedDashboardRentalsRouteImport } from './routes/_authenticated/dashboard.rentals'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard.messages'
import { Route as AuthenticatedDashboardDocumentsRouteImport } from './routes/_authenticated/dashboard.documents'
import { Route as AuthenticatedDashboardComplaintsRouteImport } from './routes/_authenticated/dashboard.complaints'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedDashboardAgreementsRouteImport } from './routes/_authenticated/dashboard.agreements'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardPropertiesIndexRouteImport } from './routes/_authenticated/dashboard.properties.index'
import { Route as AuthenticatedDashboardPropertiesNewRouteImport } from './routes/_authenticated/dashboard.properties.new'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesMapRoute = PropertiesMapRouteImport.update({
  id: '/properties/map',
  path: '/properties/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardVisitsRoute =
  AuthenticatedDashboardVisitsRouteImport.update({
    id: '/dashboard/visits',
    path: '/dashboard/visits',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSavedRoute =
  AuthenticatedDashboardSavedRouteImport.update({
    id: '/dashboard/saved',
    path: '/dashboard/saved',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRentalsRoute =
  AuthenticatedDashboardRentalsRouteImport.update({
    id: '/dashboard/rentals',
    path: '/dashboard/rentals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/dashboard/messages',
    path: '/dashboard/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDocumentsRoute =
  AuthenticatedDashboardDocumentsRouteImport.update({
    id: '/dashboard/documents',
    path: '/dashboard/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardComplaintsRoute =
  AuthenticatedDashboardComplaintsRouteImport.update({
    id: '/dashboard/complaints',
    path: '/dashboard/complaints',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/dashboard/analytics',
    path: '/dashboard/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAgreementsRoute =
  AuthenticatedDashboardAgreementsRouteImport.update({
    id: '/dashboard/agreements',
    path: '/dashboard/agreements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPropertiesIndexRoute =
  AuthenticatedDashboardPropertiesIndexRouteImport.update({
    id: '/dashboard/properties/',
    path: '/dashboard/properties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPropertiesNewRoute =
  AuthenticatedDashboardPropertiesNewRouteImport.update({
    id: '/dashboard/properties/new',
    path: '/dashboard/properties/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/map': typeof PropertiesMapRoute
  '/properties/': typeof PropertiesIndexRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/agreements': typeof AuthenticatedDashboardAgreementsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/complaints': typeof AuthenticatedDashboardComplaintsRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/rentals': typeof AuthenticatedDashboardRentalsRoute
  '/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/visits': typeof AuthenticatedDashboardVisitsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/properties/new': typeof AuthenticatedDashboardPropertiesNewRoute
  '/dashboard/properties/': typeof AuthenticatedDashboardPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/map': typeof PropertiesMapRoute
  '/properties': typeof PropertiesIndexRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/agreements': typeof AuthenticatedDashboardAgreementsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/complaints': typeof AuthenticatedDashboardComplaintsRoute
  '/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/dashboard/rentals': typeof AuthenticatedDashboardRentalsRoute
  '/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/visits': typeof AuthenticatedDashboardVisitsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/properties/new': typeof AuthenticatedDashboardPropertiesNewRoute
  '/dashboard/properties': typeof AuthenticatedDashboardPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/map': typeof PropertiesMapRoute
  '/properties/': typeof PropertiesIndexRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/agreements': typeof AuthenticatedDashboardAgreementsRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/complaints': typeof AuthenticatedDashboardComplaintsRoute
  '/_authenticated/dashboard/documents': typeof AuthenticatedDashboardDocumentsRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRoute
  '/_authenticated/dashboard/rentals': typeof AuthenticatedDashboardRentalsRoute
  '/_authenticated/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/visits': typeof AuthenticatedDashboardVisitsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/properties/new': typeof AuthenticatedDashboardPropertiesNewRoute
  '/_authenticated/dashboard/properties/': typeof AuthenticatedDashboardPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/verify-otp'
    | '/properties/$id'
    | '/properties/map'
    | '/properties/'
    | '/dashboard/admin'
    | '/dashboard/agreements'
    | '/dashboard/analytics'
    | '/dashboard/complaints'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/rentals'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/dashboard/visits'
    | '/dashboard/'
    | '/dashboard/properties/new'
    | '/dashboard/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/verify-otp'
    | '/properties/$id'
    | '/properties/map'
    | '/properties'
    | '/dashboard/admin'
    | '/dashboard/agreements'
    | '/dashboard/analytics'
    | '/dashboard/complaints'
    | '/dashboard/documents'
    | '/dashboard/messages'
    | '/dashboard/rentals'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/dashboard/visits'
    | '/dashboard'
    | '/dashboard/properties/new'
    | '/dashboard/properties'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/verify-otp'
    | '/properties/$id'
    | '/properties/map'
    | '/properties/'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/agreements'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/complaints'
    | '/_authenticated/dashboard/documents'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/rentals'
    | '/_authenticated/dashboard/saved'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/visits'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/properties/new'
    | '/_authenticated/dashboard/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesMapRoute: typeof PropertiesMapRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/map': {
      id: '/properties/map'
      path: '/properties/map'
      fullPath: '/properties/map'
      preLoaderRoute: typeof PropertiesMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/visits': {
      id: '/_authenticated/dashboard/visits'
      path: '/dashboard/visits'
      fullPath: '/dashboard/visits'
      preLoaderRoute: typeof AuthenticatedDashboardVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/saved': {
      id: '/_authenticated/dashboard/saved'
      path: '/dashboard/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof AuthenticatedDashboardSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/rentals': {
      id: '/_authenticated/dashboard/rentals'
      path: '/dashboard/rentals'
      fullPath: '/dashboard/rentals'
      preLoaderRoute: typeof AuthenticatedDashboardRentalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/dashboard/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/documents': {
      id: '/_authenticated/dashboard/documents'
      path: '/dashboard/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof AuthenticatedDashboardDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/complaints': {
      id: '/_authenticated/dashboard/complaints'
      path: '/dashboard/complaints'
      fullPath: '/dashboard/complaints'
      preLoaderRoute: typeof AuthenticatedDashboardComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/agreements': {
      id: '/_authenticated/dashboard/agreements'
      path: '/dashboard/agreements'
      fullPath: '/dashboard/agreements'
      preLoaderRoute: typeof AuthenticatedDashboardAgreementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/properties/': {
      id: '/_authenticated/dashboard/properties/'
      path: '/dashboard/properties'
      fullPath: '/dashboard/properties/'
      preLoaderRoute: typeof AuthenticatedDashboardPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/properties/new': {
      id: '/_authenticated/dashboard/properties/new'
      path: '/dashboard/properties/new'
      fullPath: '/dashboard/properties/new'
      preLoaderRoute: typeof AuthenticatedDashboardPropertiesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardAgreementsRoute: typeof AuthenticatedDashboardAgreementsRoute
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardComplaintsRoute: typeof AuthenticatedDashboardComplaintsRoute
  AuthenticatedDashboardDocumentsRoute: typeof AuthenticatedDashboardDocumentsRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRoute
  AuthenticatedDashboardRentalsRoute: typeof AuthenticatedDashboardRentalsRoute
  AuthenticatedDashboardSavedRoute: typeof AuthenticatedDashboardSavedRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardVisitsRoute: typeof AuthenticatedDashboardVisitsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardPropertiesNewRoute: typeof AuthenticatedDashboardPropertiesNewRoute
  AuthenticatedDashboardPropertiesIndexRoute: typeof AuthenticatedDashboardPropertiesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardAgreementsRoute: AuthenticatedDashboardAgreementsRoute,
  AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
  AuthenticatedDashboardComplaintsRoute: AuthenticatedDashboardComplaintsRoute,
  AuthenticatedDashboardDocumentsRoute: AuthenticatedDashboardDocumentsRoute,
  AuthenticatedDashboardMessagesRoute: AuthenticatedDashboardMessagesRoute,
  AuthenticatedDashboardRentalsRoute: AuthenticatedDashboardRentalsRoute,
  AuthenticatedDashboardSavedRoute: AuthenticatedDashboardSavedRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardVisitsRoute: AuthenticatedDashboardVisitsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardPropertiesNewRoute:
    AuthenticatedDashboardPropertiesNewRoute,
  AuthenticatedDashboardPropertiesIndexRoute:
    AuthenticatedDashboardPropertiesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesMapRoute: PropertiesMapRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
